### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by ealmloffku** [KU-EECS-348-group-R6/Truthy#3]
Described in section 4.2.2.2 in the architecture document.

Grouping groups tokens into a tree of expressions.

Major Classes:
Expression: Represents any expression tree which may contain child expressions
Operator: An enum with all operator types truthy supports

**Comment by mitch680l** [comment]
We probably need to get rid of this and possibly change our architecture plan, but honestly not sure if they would check back when they are grading.
